### ISSUE TITLE
explicit description of this project?

### ISSUE THREAD

**Issue by pjgao** [shamanez/IMU-PLOS_LSTM#1]
Hello,
I am very interested in your project, cause I am researching how to improve the positioning accuracy of IMU using LSTM.
So, what is your project? a classification problem? where did you get your data?
As I know, deep learning needs large dataset, how many data in your training?
Thanks a lot!

**Comment by shamanez** [comment]
Hi ,
Sorry for the late reply.  This is just an activity recognition task. Yes, a classification task.  Here is the [link](http://rosdok.uni-rostock.de/file/rosdok_document_0000010639/rosdok_derivate_0000037780/Documentation.pdf) for the dataset description and the task description.  Actually data set is not enough. please do not use this.
